// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace CampusFranceProject.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Création d\'un compte Campus France")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class CreationDunCompteCampusFranceFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Création d\'un compte Campus France", "  En tant qu\'utilisateur de Campus France\r\n  Je souhaite créer un compte\r\n  Afin " +
                "d\'accéder à mon espace Campus France", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "CreateAccount.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("je suis sur la page Créer un nouveau compte \"https://www.campusfrance.org/fr/user" +
                    "/register\" de Campus France", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CreateAccount.feature.ndjson", 4);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Création d\'un compte Chercheur")]
        [global::NUnit.Framework.TestCaseAttribute("Madame", "Bouhadoun", "Kenza", "France", "Algérienne", "95220", "Herblay", "0612345678", "kenza.chercheur@example.com", "cher@123456", "cher@123456", "Informatique", "Licence 1", "0", null)]
        public async global::System.Threading.Tasks.Task CreationDunCompteChercheur(string civilite, string nom, string prenom, string pays_Residence, string nationalite, string code_Postal, string ville, string telephone, string email, string mot_De_Passe, string confirmation_Mot_De_Passe, string domaine, string niveau_Etudes, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("civilite", civilite);
            argumentsOfScenario.Add("nom", nom);
            argumentsOfScenario.Add("prenom", prenom);
            argumentsOfScenario.Add("pays_residence", pays_Residence);
            argumentsOfScenario.Add("nationalite", nationalite);
            argumentsOfScenario.Add("code_postal", code_Postal);
            argumentsOfScenario.Add("ville", ville);
            argumentsOfScenario.Add("telephone", telephone);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("mot_de_passe", mot_De_Passe);
            argumentsOfScenario.Add("confirmation_mot_de_passe", confirmation_Mot_De_Passe);
            argumentsOfScenario.Add("domaine", domaine);
            argumentsOfScenario.Add("niveau_etudes", niveau_Etudes);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Création d\'un compte Chercheur", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.WhenAsync(string.Format("je renseigne les informations personnelles du chercheur \"{0}\", \"{1}\", \"{2}\"", civilite, nom, prenom), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
    await testRunner.AndAsync(string.Format("je renseigne les informations de résidence du chercheur \"{0}\", \"{1}\"", pays_Residence, nationalite), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync(string.Format("je renseigne les coordonnées du chercheur \"{0}\", \"{1}\", \"{2}\"", code_Postal, ville, telephone), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync(string.Format("je renseigne les informations de connexion du chercheur \"{0}\", \"{1}\", \"{2}\"", email, mot_De_Passe, confirmation_Mot_De_Passe), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync("je sélectionne le profil de chercheur \"Chercheur\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync(string.Format("je renseigne les informations du chercheur \"{0}\", \"{1}\"", domaine, niveau_Etudes), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.ThenAsync(string.Format("le nom renseigné est \"{0}\" pour chercheur", nom), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Création d\'un compte Institutionnel")]
        [global::NUnit.Framework.TestCaseAttribute("Monsieur", "Martin", "Thomas", "Gabon", "Algérienne", "1000", "Bruxelles", "0470123456", "thomas.martin@example.com", "insti@456789", "insti@456789", "Directeur des partenariats", "Campus France", "École Polytechnique", "1", null)]
        public async global::System.Threading.Tasks.Task CreationDunCompteInstitutionnel(
                    string civilite, 
                    string nom, 
                    string prenom, 
                    string pays_Residence, 
                    string nationalite, 
                    string code_Postal, 
                    string ville, 
                    string telephone, 
                    string email, 
                    string mot_De_Passe, 
                    string confirmation_Mot_De_Passe, 
                    string fonction, 
                    string type_Organisme, 
                    string nom_Organisme, 
                    string @__pickleIndex, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("civilite", civilite);
            argumentsOfScenario.Add("nom", nom);
            argumentsOfScenario.Add("prenom", prenom);
            argumentsOfScenario.Add("pays_residence", pays_Residence);
            argumentsOfScenario.Add("nationalite", nationalite);
            argumentsOfScenario.Add("code_postal", code_Postal);
            argumentsOfScenario.Add("ville", ville);
            argumentsOfScenario.Add("telephone", telephone);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("mot_de_passe", mot_De_Passe);
            argumentsOfScenario.Add("confirmation_mot_de_passe", confirmation_Mot_De_Passe);
            argumentsOfScenario.Add("fonction", fonction);
            argumentsOfScenario.Add("type_organisme", type_Organisme);
            argumentsOfScenario.Add("nom_organisme", nom_Organisme);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Création d\'un compte Institutionnel", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.WhenAsync(string.Format("je renseigne les informations personnelles de institutionnel \"{0}\", \"{1}\", \"{2}\"", civilite, nom, prenom), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
    await testRunner.AndAsync(string.Format("je renseigne les informations de résidence de institutionnel \"{0}\", \"{1}\"", pays_Residence, nationalite), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync(string.Format("je renseigne les coordonnées de institutionnel \"{0}\", \"{1}\", \"{2}\"", code_Postal, ville, telephone), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.AndAsync(string.Format("je renseigne les informations de connexion de institutionnel \"{0}\", \"{1}\", \"{2}\"", email, mot_De_Passe, confirmation_Mot_De_Passe), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.AndAsync("je sélectionne le profil institutionnel \"Institutionnel\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.AndAsync(string.Format("je renseigne les informations de l\'institutionnel \"{0}\", \"{1}\", \"{2}\"", fonction, type_Organisme, nom_Organisme), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.ThenAsync(string.Format("le nom renseigné est \"{0}\" pour institutionnel", nom), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
