name: Tests Selenium

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurer les dépendances
        run: dotnet restore

      - name: Compiler
        run: dotnet build --no-restore

      - name: Exécuter les tests
        run: dotnet test --no-build
